# Generated by Django 2.2.2 on 2019-10-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_channelusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel_type',
        ),
    ]
