# Generated by Django 2.2.2 on 2019-10-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_channel_channel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelusers',
            name='role',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=200),
        ),
    ]
