# Generated by Django 2.2.2 on 2019-10-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191003_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelusers',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('super_admin', 'super_admin'), ('sub_admin', 'sub_admin'), ('user', 'user')], default='admin', max_length=200),
        ),
    ]
