# Generated by Django 2.2.2 on 2019-10-03 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_channelusers_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='slug',
        ),
    ]
