# Generated by Django 2.2.2 on 2019-10-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191004_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='channel',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
    ]
