# Generated by Django 2.2.2 on 2019-10-04 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191004_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Channel')),
            ],
        ),
    ]
